name: 🐛 Bug 报告
description: 报告软件中的问题或异常行为
title: "[Bug] "
labels: ["bug", "需要分类"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间填写此 Bug 报告！🙏
        
        在提交之前，请确保：
        - ✅ 已搜索过现有 Issues，确认这不是重复报告
        - ✅ 使用的是最新版本的 QuickClipboard
        
  - type: input
    id: version
    attributes:
      label: 软件版本
      description: 你正在使用的 QuickClipboard 版本号
      placeholder: 例如：v0.0.6
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 你使用的 Windows 版本
      options:
        - Windows 11
        - Windows 10
        - Windows 其他版本
    validations:
      required: true
      
  - type: dropdown
    id: install-type
    attributes:
      label: 安装方式
      description: 你使用的安装方式
      options:
        - NSIS 安装包
        - 绿色版（便携版）
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述
      description: 清晰简洁地描述遇到的问题
      placeholder: 告诉我们发生了什么...
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 复现步骤
      description: 如何重现这个问题？
      placeholder: |
        1. 打开软件
        2. 点击 '...'
        3. 执行 '...'
        4. 看到错误
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 描述你期望发生的正常行为
      placeholder: 本应该...
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 描述实际发生的行为
      placeholder: 但实际上...
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: 截图或录屏
      description: 如果适用，添加截图或录屏来帮助说明问题
      placeholder: 拖拽图片到这里或粘贴图片链接
      
  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: 如果有错误日志或崩溃信息，请粘贴在这里
      render: shell
      
  - type: textarea
    id: additional-context
    attributes:
      label: 补充信息
      description: 添加任何其他与问题相关的信息
      placeholder: 例如：特定的使用场景、硬件配置等
      
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确认以下内容
      options:
        - label: 我已经搜索过现有的 Issues
          required: true
        - label: 我使用的是最新版本的 QuickClipboard
          required: true
        - label: 我已提供了足够的信息来重现此问题
          required: true

